version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
  branches:
    only:
      - hakyll
  - deploy:
      name: Deploy master to Github Pages
      command: |
        git config --global user.email devops@revprez.com
        git config --global user.name DevOps
        stack exec site rebuild
        git checkout master
        git pull --rebase
        cp -a _site/. .
        git add --all
        git commit -m "[`date '+%F %T %Z'`] New release"
        git push origin master:master
